apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vuepm
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vuepm
    spec:
      containers:
      - name: vuepm
        image: anveshvemula/vuepm
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
