apiVersion: v1
kind: Service
metadata:
  name: vuepm
  labels:
    app: vuepm
spec:
  selector:
    app: vuepm
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 80001
  type: LoadBalancer
